### ISSUE TITLE
Add package.json file to make it installable via npm.

### ISSUE THREAD

**Issue by jbmikk** [BlackrockDigital/startbootstrap-sb-admin#28]
It would be useful to be able to install this as an npm package. All that's required is to have a package.json at the root of the project.

**Comment by davidtmiller** [comment]
I will look into setting up npm and bower packages for this template, thanks.

**Comment by ssteinerx** [comment]
@davidtmiller I'm working on another project [django-sb-admin](https://github.com/ssteinerx/django-sb-admin) that used a *copy* of this as its base and am working on using npm/bower/grunt to get it installing the various parts instead of the 

`$ extremely-tedious-manual-maintenance` 

model used originally.  

Please ping me if you'd like to collaborate as I've been deep into this stuff for the last few days and while it's not hard, it can be kind of annoying and time-consuming if you've not done it before...or not done it in the last week, since there's *so much stuff to remember* every time.

**Comment by davidtmiller** [comment]
package.json and NPM package now exists and will update automatically as new releases are published.
