### ISSUE TITLE
Difference between SB Admin and SB Admin 2

### ISSUE THREAD

**Issue by danilose** [BlackrockDigital/startbootstrap-sb-admin#66]
What is the difference between SB Admin and SB Admin 2?

**Comment by sinfuljosh** [comment]
SB Admin 2 is still using Bootstrap framework 3.3.7 as seen in the css and js files being used. 

 * Bootstrap v3.3.7 (http://getbootstrap.com)

There are also different third party plugins being used in SB Admin 2 that are not part of SB admin. 

Ultimately, SB Admin is using the newer Bootstrap framework and is a cleaner base admin template to start with if you plan on adding your own third party scripts or plugins. While SB Admin 2 has more functionality thanks to the third party plugins, it is also better suited for supporting some older browsers (mainly IE 8) since I believe the new bootstrap's css its based off of flex, which was not standard back then for browsers.

**Comment by davidtmiller** [comment]
Long story short, SB Admin is a baseline template with very little custom design added to it. It serves as a toolkit for developers to use in order to start a project, but not a pre-designed theme.

SB Admin 2 _will be_ using SB Admin as a dependency, and will then add/overwrite SB Admin and Bootstrap as needed in order to become a fully designed admin theme, as opposed to an admin template (or layout).

Hopefully this clears things up. With the release of SB Admin v5.0.0 I am getting closer to updating SB Admin 2 - which may get a name change as well because it might get a little confusing if there is an SB Admin v5 and an SB Admin 2 v5...

**Comment by knweiss** [comment]
What about a FAQ section in the `README.md` of both sb-admin and sb-admin-2 where you explain this relationship of both projects?
