### ISSUE TITLE
fixed-nav

### ISSUE THREAD

**Issue by tomalessi** [BlackrockDigital/startbootstrap-sb-admin#85]
I am seeing three issues when trying to use a fixed side-nav by adding the `.fixed-nav` class on the body element :

1. The `.sidebar.fixed-top` element is 6 pixels too tall and pushes into the top nav.  Setting it to 62px solves the issue.  Looks like this gets set from the $navbar-base-height var.

2. The `body.fixed-nav #content-wrapper` receives a `margin-top` of 56 pixels, which is not required.  This pushes the main content down too far.

3. When the side menu is toggled, and there is a drop-down menu, the menu cannot "pop out" of the parent <ul> because it has an overflow.  There is not an easy workaround for this and this one is a showstopper to having the side-nav be in a fixed position. 

Note: I also added the `.fixed-top` class to the sidebar.

**Comment by davidtmiller** [comment]
1. Are you customizing the top navigation at all by adding a logo or changing the font or anything like that? If so that might be the culprit, otherwise I'll check into this.

2. Add `.fixed-top` the the main navigation element as well - that's why the extra 56px is there on the content wrapper.

3. Ah crap...I think you are correct that this is a show stopper - not being able to use drop downs on a fixed nav is a bit of a limitation. I will need to explore on how to rework this, but for now I just don't have the bandwidth. If you wanted to take a stab at this though then I would be very appreciative. Creating these sidebar menus that work in all situations has proven way more complicated than it looks...

**Comment by Spegeli** [comment]
For me the fixed nav and sidebar works fine except the issue with the drop down not opening.
i dont think there is already solution for this?

**Comment by davidtmiller** [comment]
The fixed nav isn't going to work when I handle the dropdowns in the current fashion. For the time being I will be disabling the fixed nav option, and will revisit fixed navs at some point in the future when I have the time.

**Comment by davidtmiller** [comment]
cc1a86286617d6dff0df3942ae831d8595158d7e has changed the nav behavior and now includes a much better fixed nav option
