### ISSUE TITLE
Change & Reposition SidebarToggle icon

### ISSUE THREAD

**Issue by ejones31** [BlackrockDigital/startbootstrap-sb-admin#89]
Currently, the icon for collapsing the sidenavbar is the ubiquitous hamburger icon (_fa-bars_). 
Our user testing shows users expect a menu to appear when clicking that icon. The actual results do not meet expectations. They have to discover the functionality by accident.
We've kicked it around, and the best solution has two parts:
1. Move the icon to the bottom of the navigation menu on sidenavbar.
2. Change the icon from  _fa-bars_ to use _fa-angle-double-left_, when menu is open, and _fa-angle-double-right_, when the menu is closed.

**Comment by davidtmiller** [comment]
So this works when the sidebar is present at all times (even in its toggled state) but there would need to be the bars when the page is mobile and below since the sidebar disappears entirely on smaller screens.

I'll revisit this when I have time and implement a clear solution for the sidebar toggle button along with a responsive option.

**Comment by davidtmiller** [comment]
v6 changes this behavior
